version: '1.0'
services:
  postonapp:
    image: 'poston-api'
    container_name: 'postonapp'
    restart: 'always'
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: postondb
    depends_on:
      - mysql

  mysql:
    image: 'mysql:latest'
    container_name: 'postondb'
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poston_db
    ports:
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/dump.sql


