version: '1.0'
services:
  mysql:
    image: 'mysql:latest'
    container_name: 'post-on-db'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poston_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data:
    driver: local